name    'a2tar-openvpn'
version '0.1.0'
source 'https://github.com/a2tar/openvpn.git'
author 'A2TaR'
license 'MIT License'
summary 'puppet module: openvpn server on ubuntu'
description ''
project_page 'https://github.com/a2tar/openvpn'

dependency 'attachmentgenie/ufw', '>= 1.2.0'
dependency 'puppetlabs/apt', '>= 1.4.0'
dependency 'a2tar/dnsmasq', '0.1.0'
dependency 'a2tar/sysctl', '>= 0.1.0'
