name 'a2tar-openvpn'
version '0.1.3'
author 'A2TaR'
license 'MIT License'
source 'https://github.com/a2tar/openvpn.git'
project_page 'https://github.com/a2tar/openvpn'
summary 'puppet module: openvpn server on ubuntu'
dependency 'a2tar/dnsmasq', '>= 0.1.6'
dependency 'a2tar/sysctl', '>= 0.1.0'
dependency 'puppetlabs/apt', '>= 1.4.0'
dependency 'attachmentgenie/ufw', '>= 1.2.0'
